//
// Created by Lelana on 2026. 2. 28..
//

#ifndef LINEARDATASTRUCTURE_QUEUESTACK_QUEUE_H
#define LINEARDATASTRUCTURE_QUEUESTACK_QUEUE_H


class Queue {
};


#endif //LINEARDATASTRUCTURE_QUEUESTACK_QUEUE_H