//
// Created by Lelana on 2026. 2. 28..
//

#ifndef LINEARDATASTRUCTURE_QUEUESTACK_UNDOREDOSYSTEM_H
#define LINEARDATASTRUCTURE_QUEUESTACK_UNDOREDOSYSTEM_H


class UndoRedoSystem {
};


#endif //LINEARDATASTRUCTURE_QUEUESTACK_UNDOREDOSYSTEM_H